# 토큰 정보 설정
token:
  expiration_time: 86400000 # 60초 * 60분 * 24시간 * 1000
  secret: my_token_default_chaged_n1

gateway:
  ip: 172.30.1.37

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: 주문이 존재하지 않습니다.

test:
  greeting: 테스트 완료