# 토큰 정보 설정
token:
  expiration_time: 86400000 # 60초 * 60분 * 24시간 * 1000
  secret: my_token_default_chaged_n1

gateway:
  ip: 172.30.1.37

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders

hello:
  test: test
  test2: test

hello2:
  test: test